Initial docs for project issue processes
operator-framework/operator-sdk pull request #3952
Opened 2020-09-28 17:52 UTC by asmacdo

2020-09-29 02:16 UTC, jmrodri requested changes
Just a minor url change.

2020-09-29 02:16 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/issue-lifecycle.md
> +issues](https://github.com/operator-framework/operator-sdk/issues).
You can keep your lines short by putting the urls at the bottom of the document. 
```
[GitHub issues][gh-issues]

...
[gh-issues](https://github.com/operator-framework/operator-sdk/issues)
```
We've done that in a number of places.

2020-09-29 02:16 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/issue-lifecycle.md
> +meeting](https://github.com/operator-framework/community/#operator-sdk-community-issue-triagegrooming)
use the advice from above regarding urls.

2020-09-29 02:16 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/issue-lifecycle.md
> +to a Milestone. Additionally, anyone can request that a previously
would it be helpful to link to `Milestone`?  https://github.com/operator-framework/operator-sdk/milestones

2020-10-01 21:16 UTC, jberkhahn commented
seems fine
/lgtm

2020-10-02 18:36 UTC, camilamacedo86 approved these changes
It shows fine for me as well 👍 
/lgtm

2020-10-02 19:07 UTC, merged