Setting GO111MODULE=on is not required with go version 1.13 and later
operator-framework/operator-sdk pull request #4058
Opened 2020-10-18 10:43 UTC by fgiloux

Rational:
https://golang.org/doc/go1.13
The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src.

2020-10-18 12:20 UTC, camilamacedo86 requested changes
Hi @fgiloux, 

Really thank you for your collaboration. Note that we cannot push this change because the previous go versions are not supported. Also, it is possible to run `export GO111MODULE=off`. In this way, in POV the current text is valid.  

So, IHMO I think we should not merge this change.

2020-10-18 15:48 UTC, fgiloux commented
Hi @camilamacedo86 

thanks for the quick feedback and pointed out that go versions prior to 1.13 are not supported. To be frank I would just remove the sentence. As defaults are just working I feel like this is just a distraction to the reader wanted to go through the tutorial. Also this is nothing specific to operator-sdk and the very few readers having a shell diverging from the defaults should already be well versed in the subject.

If you agree on that I can amend the pull request otherwise feel free to close it.

2020-10-19 21:09 UTC, camilamacedo86 commented
Hi @fgiloux, 

> To be frank I would just remove the sentence.

I would be ok with that if we address the error scenario issue faced in the FAQ. See; https://sdk.operatorframework.io/docs/faqs/faqs/. WDYT? Would be interesting on working on that in this PR?

2020-10-19 21:32 UTC, joelanford commented
IMO, that sentence helps clarify environment requirements for Go beginners.

Go experts will probably understand or at least know to lookup the details of the GO111MODULE variable and decide how to set it for themselves, but Go beginners are probably happy to be told to explicitly set GO111MODULE=on even if it's unnecessary.

That sentence is still applicable to Go1.13+ because users may have explicitly set `GO111MODULE=off`, which would likely cause their SDK-based operator not to compile.

My vote would be to close this with no change.

2020-10-19 21:39 UTC, camilamacedo86 commented
Hi @fgiloux, 

Really thank you for your collab. I hope that you are ok with us close to this one. 
However, please your PR's are more than welcome.

2020-10-19 21:39 UTC, closed without merging