Update kb 9c02d557f01b-to-b6a0bf1b6040
operator-framework/operator-sdk pull request #4215
Opened 2020-11-10 12:28 UTC by camilamacedo86

**Description of the change:**
- Update kubebuilder dependency (See: https://github.com/kubernetes-sigs/kubebuilder/compare/9c02d557f01b...b6a0bf1b6040)
- Align SDK with Kubebuilder and address bug fixes

**Motivation for the change:**
- Solve tech-debt and keep both projects aligned

2020-11-10 20:06 UTC, jmrodri commented
I retitled this PR it used to be called `Update kb 9c02d557f01b-to-b6a0bf1b6040` I changed it to `Update kubebuilder to commit b6a0bf1b6040`

2020-11-10 20:06 UTC, jmrodri approved these changes
/lgtm

2020-11-10 22:44 UTC, jberkhahn commented
would be nice to wait until [1711](https://github.com/kubernetes-sigs/kubebuilder/pull/1711) is merged, but oh well :/

2020-11-11 11:03 UTC, camilamacedo86 commented
Hi @johananl, 

 > would be nice to wait until 1711 is merged, but oh well :/

I cannot see any no reason for we wait for any specific new fix or change in the Kubebuilder side.
See that the idea is we keep both aligned. If we do not keeping doing this update then, when we do that we will need to perform so many changes to bump that it will be very complex to get done.

2020-11-11 13:00 UTC, johananl commented
@camilamacedo86 wrong tag ;-) Tagging @jberkhahn.

2020-11-13 21:14 UTC, estroz requested changes
Two nits, overall LGTM

2020-11-13 21:14 UTC, estroz commented on changelog/fragments/update-kb-from-9c02d557f01b-to-c158f4fa4207.yaml
> +      More info: https://github.com/kubernetes-sigs/kubebuilder/pull/1770
The "More info: [link]" string is too verbose. I say we stick to the `([kubebuilder#X](https://github.com/kubernetes-sigs/kubebuilder/pull/))` format, ex.
```suggestion
      (go/v2) Fixed controller imports scaffolded by `create api` when `--resource=false`
      ([kubebuilder#1770](https://github.com/kubernetes-sigs/kubebuilder/pull/1770))
```

2020-11-13 21:14 UTC, estroz commented on internal/plugins/golang/v2/plugin.go
> +	_ plugin.Edit          = Plugin{}
```suggestion
	_ plugin.Full          = Plugin{}
```

2020-11-13 21:24 UTC, camilamacedo86 commented on internal/plugins/golang/v2/plugin.go
> +	_ plugin.Edit          = Plugin{}
Good cather 👍

2020-11-13 21:30 UTC, estroz approved these changes
/lgtm

2020-11-13 22:24 UTC, merged