*: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .'
operator-framework/operator-sdk pull request #4226
Opened 2020-11-11 20:16 UTC by wking

Because folks may have `docker` aliased to `podman`, and Podman prefers options before positional arguments:

```console
$ podman build --help | grep CONTEXT-DIRECTORY
   podman build [command options] CONTEXT-DIRECTORY | URL
```

Generated with:

```console
$ sed -i 's/docker build . -t ${IMG}/docker build -t ${IMG} ./' $(git grep -l 'docker.*build \. ')
```

2020-11-11 20:22 UTC, joelanford commented
Seems reasonable to me. If applicable, we should also make this change upstream in the Kubebuilder plugins so we can pull the same change in for Go projects.

2020-11-11 20:22 UTC, camilamacedo86 reviewed
Hi @wking, 

Thank you for your suggestion. However, we have 3 types of operators that are built with the tool and in order to keep its maintainability and give a better user experience, I do not think that we should change the common targets only for Ansible. 

So, to move forward with this change IHMO we need to first push it to upstream/kubebuiler. See: https://github.com/kubernetes-sigs/kubebuilder. 

Then, when a new version of the upstream/kb be bumped here we can also apply these changes for the other types as well. 

However, before you push your suggestion to upstream could you please clarifies better what use case it will address? Sorry, but I did not get what is not possible to do currently with `docker build . -t ${IMG}` that will be solved with the replace `docker build -t ${IMG} .`

2020-11-11 21:55 UTC, wking commented
Podman folks talking about this in containers/podman#2811.

> I do not think that we should change the common targets only for Ansible.

In this PR, I'm changing everything that matched my `sed`.  Did I miss an entry?  I will file an upstream PR.

2020-11-11 22:00 UTC, wking commented
Upstreamed as kubernetes-sigs/kubebuilder#1817

2020-11-18 05:05 UTC, wking commented
Upstream PR landed.  Do we pull the hold here, or is there another way to ingest the upstream change?

2020-11-23 15:39 UTC, jmrodri approved these changes
/lgtm

2020-11-23 15:46 UTC, camilamacedo86 requested changes
IMO we should not merge this one. 
This change was made for v3/go-alpha (kubebuilder/upstream see: ). In this way, when SDK starts to support Golang v3/alpha then, we need to create the v2+ plugins for Ansible/Helm where the changes made for v3 would be applied to them as well. At this moment this change will be applied for these types.

2020-11-23 16:11 UTC, joelanford commented
Despite the upstream conversation to the contrary, I don't think I would consider this a change that needs to be held until a new version of the ansible and helm plugins are released. IMO, we should have pushed harder for this to be backported to the Go v2 plugin upstream. I also don't think the upstream decision binds our downstream decision.

There are always going to be differences between the different language plugins, and I think we can make our own decisions about what features and fixes to include in the helm and ansible plugins even if upstream is very conservative about what constitutes a breaking change in the Go plugin's scaffolded files.

I think I'm a :+1: to getting this merged.

2020-11-23 16:17 UTC, camilamacedo86 commented
Hi @wking,

See that for it get merged it needs to pass in the CI. It is falling in the `make test-sanity`. to fix that you need to run `make generate`.

2020-11-23 16:18 UTC, camilamacedo86 commented on internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
Also, it is missing the fragment. Changelog.

2021-02-03 00:45 UTC, jmrodri commented
Closing this in favor of PR #4466 to avoid the constant back and forth.

2021-02-03 00:45 UTC, closed without merging