fix swapped liveness/readiness http paths. (#4541)
operator-framework/operator-sdk pull request #4546
Opened 2021-02-17 08:07 UTC by flozzone

* created changelog fragment
* fixed scaffold template for the manager resource (ansible/helm)
* fixed testdata (ansible/helm)

Signed-off-by: Florin Hillebrand <flozzone@gmail.com>

**Description of the change:**

Fix wrong HTTP paths of the livenessProbe and readinessProbe in the scaffold templates and testdata.

**Motivation for the change:**

livenessProbe and readinessProbe were swapped in templates but are correctly documented in upgrade guide.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [X] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2021-02-17 08:09 UTC, flozzone commented
Is it ok, having two PRs referencing the same issue? #4545 and #4546

2021-02-17 17:49 UTC, estroz requested changes
Just two changelog nits, thanks @flozzone!

2021-02-17 17:49 UTC, estroz commented on changelog/fragments/swap-readiness-liveness-paths-4541.yaml
> +      created with operators-sdk >= v1.4.0.
The version is implied by the release notes this fragment will be a part of.
```suggestion
      For Ansible/Helm-based operators, fix swapped readinessProbe/livenessProbe in manager
```

2021-02-17 17:49 UTC, estroz commented on changelog/fragments/swap-readiness-liveness-paths-4541.yaml
> +        following probes in the deployment resource for the manager:
```suggestion
        The liveness and readiness probe endpoints were incorrectly named, although this mismatch will not affect their behavior.
        To fix, swap the `readinessProbe` and `livenessProbe` HTTP paths in `config/manager/manager.yaml`:
```

2021-02-17 18:21 UTC, flozzone commented
You @estroz also cleared something up for me, thanks :)

2021-02-17 18:51 UTC, estroz commented on changelog/fragments/swap-readiness-liveness-paths-4541.yaml
> +        following probes in the deployment resource for the manager:
This change hasn’t been adopted yet.

2021-02-18 08:39 UTC, estroz approved these changes
/lgtm

2021-02-18 08:40 UTC, merged