ansible/helm: add ssc to not allow root previleges
operator-framework/operator-sdk pull request #4655
Opened 2021-03-13 15:21 UTC by camilamacedo86

Signed-off-by: Camila Macedo <cmacedo@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2021-03-13 15:35 UTC, camilamacedo86 commented on testdata/ansible/memcached-operator/config/manager/manager.yaml
> +      - command:
just organize as the other plugins to being easier we check the differences by doing diffs in the files.

2021-03-13 15:36 UTC, camilamacedo86 commented on testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
> +                command:
Just to follow the standard. I did not add to the migration steps because it is optional.

2021-03-15 20:37 UTC, estroz requested changes

2021-03-15 20:37 UTC, estroz commented on changelog/fragments/ansible-helm-ssc.yaml
> +      (ansible/v1)(helm/v1) Add SecurityContext to now allow root privileges.
```suggestion
      (ansible/v1, helm/v1) Added `securityContext`'s to the manager's Deployment to disallow running as root user.
```

2021-03-15 20:37 UTC, estroz commented on changelog/fragments/ansible-helm-ssc.yaml
> +      header: (ansible/v1)(helm/v1) **(Optional)** Add SecurityContext to now allow root privileges.
All `v1.y` migrations are optional.
```suggestion
      header: (ansible/v1, helm/v1) Add `securityContext`'s to your manager's Deployment.
```

2021-03-15 20:37 UTC, estroz commented on changelog/fragments/ansible-helm-ssc.yaml
> +        In the `config/manager` add the following security context:
```suggestion
        In `config/manager/manager.yaml`, add the following security contexts:
```

2021-03-15 20:37 UTC, estroz commented on changelog/fragments/ansible-helm-ssc.yaml
> +        spec:
Can you indent these from the root field, ex
```yaml
spec:
  ...
  template:
    ...
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        securityContext:
          allowPrivilegeEscalation: false
```

2021-03-15 23:06 UTC, estroz approved these changes
/lgtm

2021-03-16 01:21 UTC, merged