Run generate before prerelease
operator-framework/operator-sdk pull request #4952
Opened 2021-05-27 17:03 UTC by fabianvf

**Description of the change:**
`make generate` is now run before `make prerelease`, and the documentation is updated to match.

**Motivation for the change:**
This is a necessary step in the release process.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2021-05-27 19:01 UTC, estroz approved these changes
/lgtm

2021-06-10 03:22 UTC, jmrodri requested changes
Looks just fine except for the typo.

2021-06-10 03:22 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/releasing.md
> +- `Makefile`: IMAGE_VERSION should be modified to the upcoming release tag. (This variable ensures sampleprojects have been tagged correctpy prior to the release commit.)
```suggestion
- `Makefile`: IMAGE_VERSION should be modified to the upcoming release tag. (This variable ensures sampleprojects have been tagged correctly prior to the release commit.)
```

2021-06-10 03:22 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/releasing.md
> +git add Makefile changelog website testdata
+1

2021-06-10 03:22 UTC, jmrodri commented on website/content/en/docs/contribution-guidelines/releasing.md
> +git add Makefile changelog website testdata
+1

2021-09-03 20:24 UTC, jmrodri commented
Fixing typo will allow me to approve this.

2021-11-12 19:59 UTC, jmrodri approved these changes
/lgtm

2021-11-12 19:59 UTC, merged