Flesh out how to handle resources on deletion.
operator-framework/operator-sdk pull request #5069
Opened 2021-07-19 08:49 UTC by fgiloux

**Description of the change:**

This change aims to enhance the documentation by providing more detailed instructions under advanced topics on how to handle resource deletion, going through multiple scenarios.
It also add a couple of lines to the best practices section to refer to it.

**Motivation for the change:**

Handling resources on deletion is an important topic. Accumulating resources without boundaries can have a very negative impact not only for the culprit operator but the complete cluster.

2021-07-21 17:26 UTC, estroz requested changes
Great content, needs grammatical work though. Thanks for the contribution!

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +Similar to the previous scenario finalizers can be used for implementing complex cleanup logic. Taking cron jobs as an example. They require to keep a number of past jobs, which have been spawned by
```suggestion
Similar to the previous scenario, finalizers can be used for implementing complex cleanup logic. Take [CronJobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) as an example: the controller maintains limited-size lists of jobs that have been created by the CronJob controller to check for deletion. These list sizes are configured by the CronJob fields [`.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit`](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits), which specify how many completed and failed jobs should be kept. Check out the [Kubebuilder CronJob tutorial](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#3-clean-up-old-jobs-according-to-the-history-limit) for full implementation details.
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +Sensitive resources need to be protected against unintended deletion. One typical example is Persistent Volume (PV) / Persistent Volume Claim (PVC). If a user tries to delete a PV that is bound by a
```suggestion
Sensitive resources need to be protected against unintended deletion. An intuitive example of protecting resources is the [PersistentVolume (PV) / PersistentVolumeClaim (PVC)](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) relationship. A PV is first created, after which users can request access to that PV's storage by creating a PVC, which gets bound to the PV. If a user tries to delete a PV currently bound by a PVC, the PV is not removed immediately. Instead, PV removal is postponed until the PV is not bound to any PVC. Finalizers again can be leveraged to achieve a similar behaviour for your own PV-like custom resources: by setting a finalizer on an object, your controller can make sure there are no remaining objects bound to it before removing the finalizer and deleting the object.
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +In the other direction the user can specify what happens to a PV when the PVC is deleted through the reclaim policy. There are two options: "delete", which means that the PV is deleted or retain, whe
```suggestion
Additionally, the user who created the PVC can specify what happens to the underlying storage allocated in a PV when the PVC is deleted through the [reclaim policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming). There are several options available, each of which defines a behavior that is achieved again through the use of finalizers. The key concept to take away is that your operator can give a user the power to decide how their resources are cleaned up via finalizers, which may be dangerous yet useful depending on your workloads.
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +**Internal Resources**
```suggestion
#### Internal Resources
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +**External Resources**
```suggestion
#### External Resources
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +**Complex cleanup logic**
```suggestion
#### Complex cleanup logic
```

2021-07-21 17:26 UTC, estroz commented on website/content/en/docs/building-operators/golang/advanced-topics.md
> +**Sensitive resources**
```suggestion
#### Sensitive resources
```

2021-07-22 04:51 UTC, fgiloux commented
Thanks @estroz for correcting the grammar and improving readability. I have accepted all the recommendations.

2021-07-22 20:23 UTC, estroz approved these changes
/lgtm

2021-07-22 20:24 UTC, merged

2021-07-27 13:11 UTC, rashmigottipati commented on website/content/en/docs/building-operators/golang/advanced-topics.md
>  import (
@estroz sure, will create a PR to rewrite the example to use the finalizer library.