Adding sort to reorder webhookDescription based on webhookType
operator-framework/operator-sdk pull request #5177
Opened 2021-08-27 17:37 UTC by sujil02

Adding sort to reorder webhookDescription based on webhookType
https://issues.redhat.com/browse/OSDK-1916

#5022 
Signed-off-by: sujil02 <sujil.shah@gmail.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2021-08-28 18:34 UTC, camilamacedo86 requested changes
Hi @sujil02, 

For your contribution to be accepted you need to:
- Add [changelog entry](https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml) to generate the release notes. 
- Run [make generate](https://github.com/operator-framework/operator-sdk/blob/master/Makefile#L39) that will re-gen the docs and the samples in the testdata.

2021-08-30 17:26 UTC, sujil02 commented
> Hi @sujil02,
> 
> For we are able to merge your contribution you need to:
> 
> * Add [changelog entry](https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml) to generate the release notes.
> * Run [make generate](https://github.com/operator-framework/operator-sdk/blob/master/Makefile#L39) that will re-gen the docs and the samples in the testdata.

Done.

2021-08-30 23:41 UTC, varshaprasad96 reviewed
just a small nit, looks good.
/lgtm

2021-08-30 23:41 UTC, varshaprasad96 commented on changelog/fragments/fix_order_of_generated_webhooks.yaml
> +      Ensuring generated webhook order is stable.
```suggestion
      Preserve the order of `webhookdefinitions` while generating bundles, by sorting `webhookDescriptions` in CSV generator.
```

2021-08-31 07:32 UTC, sujil02 commented on changelog/fragments/fix_order_of_generated_webhooks.yaml
> +      Ensuring generated webhook order is stable.
Fixed. Thank you.

2021-08-31 17:37 UTC, rashmigottipati approved these changes
/lgtm

2021-09-01 20:22 UTC, camilamacedo86 commented on changelog/fragments/fix_order_of_generated_webhooks.yaml
> +    breaking: false
nit space

2021-09-01 20:25 UTC, camilamacedo86 approved these changes
/lgtm

2021-09-01 20:59 UTC, camilamacedo86 reviewed
/lgtm

2021-09-01 21:07 UTC, sujil02 commented on changelog/fragments/fix_order_of_generated_webhooks.yaml
> +    breaking: false
Fixed.

2021-09-07 13:46 UTC, merged