Add hybrid helm binary to operator-sdk
operator-framework/operator-sdk pull request #5504
Opened 2022-01-17 21:11 UTC by varshaprasad96

**Description of the change:**
Add hybrid helm binary to operator-sdk

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2022-01-17 21:12 UTC, varshaprasad96 commented
cc: @fabianvf

2022-01-17 21:13 UTC, varshaprasad96 commented
This can go in only after SDK is bumped to use k8s 1.23, which happens here: https://github.com/operator-framework/operator-sdk/pull/5503

2022-01-21 20:02 UTC, fabianvf requested changes

2022-01-21 20:02 UTC, fabianvf commented on internal/util/projutil/project_util.go
> +	operatorTypeHybrid OperatorType = "hybrid"
can we make this `hybrid.helm`/`hybrid+helm`/`hybrid-helm` or something like that, since it's possible we'll see more hybrid plugins in the future?

2022-01-21 20:02 UTC, fabianvf commented on internal/util/projutil/project_util.go
> +		case strings.HasPrefix(pluginKey, "hybrid"):
same here, should probably key it to hybrid.helm or whatever

2022-01-24 20:28 UTC, fabianvf approved these changes
lgtm, go-e2e tests failed so I rekicked to see if it's just a flake

2022-01-24 21:42 UTC, jmrodri approved these changes
/lgtm

2022-01-24 21:42 UTC, merged