add faq info about bundle size
operator-framework/operator-sdk pull request #5559
Opened 2022-02-22 21:53 UTC by camilamacedo86

add faq info about bundle size

2022-02-22 21:59 UTC, asmacdo requested changes
lgtm other than the removal of the note about OpenShift versions.

2022-02-22 21:59 UTC, asmacdo commented on website/content/en/docs/faqs/_index.md
> +_NOTE: Openshift k8S vendor began to allow `~4MB` uncompressed bundle sizes from its `4.9` version release version._
We should not mention OpenShift

2022-02-23 00:17 UTC, camilamacedo86 commented on website/content/en/docs/faqs/_index.md
> +_NOTE: Openshift k8S vendor began to allow `~4MB` uncompressed bundle sizes from its `4.9` version release version._
```suggestion
```

2022-02-23 00:24 UTC, asmacdo approved these changes
/lgtm

2022-02-23 00:48 UTC, merged