OSDK-2345: Export scorecard storage as an env variable in a test pod
operator-framework/operator-sdk pull request #5829
Opened 2022-06-02 14:12 UTC by apodhrad

Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

2022-06-03 02:27 UTC, jmrodri requested changes
Minor formatting issue. Other than that I think this is a good idea.

2022-06-03 02:27 UTC, jmrodri commented on internal/scorecard/storage.go
> +        mountPathEnv := v1.EnvVar{
this fails `go fmt`. Should be a TAB.
```suggestion
     mountPathEnv := v1.EnvVar{
```

2022-06-07 20:55 UTC, jmrodri commented
@apodhrad sadly you forgot to sign the latest commit. It is failing DCO check. You will have to do a rebase with `--signoff` to fix it, something like this `git rebase HEAD~2 --signoff`

2022-06-07 20:55 UTC, jmrodri approved these changes

2022-06-07 20:57 UTC, jmrodri commented
@apodhrad actually this PR warrants a changelog entry. https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml explaining this addition.

2022-07-13 15:48 UTC, jmrodri approved these changes
/lgtm

2022-07-13 16:40 UTC, theishshah approved these changes
Looks good, shouldn't break existing storage functionality

2022-07-13 17:07 UTC, merged