:bug: fix operator-sdk generate kustomize manifests to respect changes made by users in the config/manifests
operator-framework/operator-sdk pull request #5960
Opened 2022-07-30 09:05 UTC by camilamacedo86

Signed-off-by: Camila Macedo <cmacedo@redhat.com>

**Description of the change:**

 fix operator-sdk generate kustomize manifests to respect changes made by users in the config/manifests

**Motivation for the change:**

If we change the target value on the command to solve the breaking change faced with Kustomize v4 it still not working
because the SDK subcommand call the Helper plugin to generate the CSV and it was not configured to Skip the file when it is scaffolded already.  

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [x] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

Motivation: https://github.com/operator-framework/operator-sdk/issues/5898

2022-08-01 13:23 UTC, everettraven requested changes
Just a couple minor wording nits on the docs. Other than that looks great! Thanks Camila!

2022-08-01 13:23 UTC, everettraven commented on website/content/en/docs/faqs/_index.md
> +## After update my project to use a Kustomize 4.x version the make bundle does not properly work
Nit:
```suggestion
## After updating my project to use a Kustomize 4.x version, 'make bundle' does not work
```

2022-08-01 15:10 UTC, camilamacedo86 commented on website/content/en/docs/faqs/_index.md
> +are no longer added at the same order. To sort it out you can update replace the target `/spec/template/spec/containers/1/volumeMounts/0`
I think replace is better because it makes clear the instruction as we do in the migration guides.

2022-08-01 16:18 UTC, laxmikantbpandhare approved these changes
/lgtm

2022-08-05 18:04 UTC, everettraven approved these changes
/lgtm

2022-08-08 15:31 UTC, merged