Remove duplicated step for upgrading to 1.23.0
operator-framework/operator-sdk pull request #6003
Opened 2022-08-25 07:29 UTC by iblancasa

Signed-off-by: Israel Blancas <iblancasa@gmail.com>

**Description of the change:**
One step in the `upgrading to 1.23.0` section is duplicated.

**Motivation for the change:**
Solves #6002.

2022-08-25 13:53 UTC, everettraven requested changes
Hi @iblancasa! Thanks so much for the contribution!

The reason for this migration step showing up twice is because there were separate commits that introduced migration steps for the upgrade from v0.11.0 -> v0.12.0 and v0.12.0 -> v0.13.0.

I agree that we should convert it to a single step, however I don't think just removing the v0.11.0 -> v0.12.0 step is ideal.

I think ideally we would remove one of them but adapt the other to be a migration from v0.11.0 -> v0.13.0. We could make a single migration step that looks like:
```markdown
## Upgrade kube proxy image `gcr.io/kubebuilder/kube-rbac-proxy` from `v0.11.0` to `v0.13.0`

In the `config/default/manager_auth_proxy_patch.yaml` file, replace `gcr.io/kubebuilder/kube-rbac-proxy:0.11.0` with `gcr.io/kubebuilder/kube-rbac-proxy:0.13.0`

_See [#5903](https://github.com/operator-framework/operator-sdk/pull/5903) and [#5965](https://github.com/operator-framework/operator-sdk/pull/5965) for more details._
```

2022-08-25 14:29 UTC, iblancasa commented
Ok, @everettraven  I'll do it :)
Thanks for your feedback

2022-08-26 10:32 UTC, camilamacedo86 approved these changes

2022-08-26 16:29 UTC, everettraven approved these changes
/lgtm

2022-08-26 16:30 UTC, merged