change nongo bundle generation cruft to use updated flags
operator-framework/operator-sdk pull request #6014
Opened 2022-09-02 21:05 UTC by jberkhahn

Fixes #5987

Took a look at this and it looks like it should be fine.

2022-09-06 17:04 UTC, jberkhahn commented
hey could you take a look at this @jmrodri ? You wrote the original change for the go stuff

2022-09-06 18:58 UTC, everettraven approved these changes
Looks good to me, but because I am unfamiliar with the reasoning for only having this done in the Go plugin in the past I will leave a LGTM up to @jmrodri or others that are familiar with it.

2022-09-19 18:15 UTC, varshaprasad96 requested changes

2022-09-19 18:15 UTC, varshaprasad96 commented on internal/plugins/manifests/v2/init.go
> +	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle $(BUNDLE_GEN_FLAGS)
Can we leave the `--overwrite` flag as is. Removing it will affect the user experience.

2022-09-19 18:17 UTC, jmrodri approved these changes
/lgtm

2022-09-19 18:19 UTC, varshaprasad96 commented on internal/plugins/manifests/v2/init.go
> +	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle $(BUNDLE_GEN_FLAGS)
Ah! missed it! Sounds good!

2022-09-19 18:19 UTC, varshaprasad96 approved these changes
/lgtm

2022-09-19 18:20 UTC, merged