Set REST timeout when timeout cli arg is provided
operator-framework/operator-sdk pull request #6440
Opened 2023-05-19 14:11 UTC by sebsoto

**Description of the change:**
The timeout arg sets the overall timeout for the full command to finish, such as `run bundle`, but it doesn't affect the timeout of individual API server requests. This remains the default timeout specified in the API server configuration. This means that even if a user wants `run bundle` to timeout after 5m, the command may return earlier due to an individual request's timeout being hit.

This commit fixes that behavior by setting the Timeout value in the client cfg to the value passed in by the user, this will prevent the individual request from timing out before the desired timeout.

**Motivation for the change:**
operator-sdk bundle run fails on operators that take longer than usual to install

2023-05-22 14:17 UTC, everettraven requested changes
@sebsoto Thanks for taking the time to write up this contribution! Overall I think the change suggested is reasonable, but I think the existing change doesn't actually address this. I left a comment that elaborates on this a bit more:

2023-05-22 14:17 UTC, everettraven commented on internal/olm/installer/manager.go
So I think this sounds like a reasonable change, however I think this is being done in the wrong file based on the context given in the PR description. This configuration is only for the `operator-sdk olm install` command and doesn't apply broadly to all commands.

I can see an argument for applying this more broadly but based on the PR description this change seems to be more focused on updating `operator-sdk run bundle` and I'd personally prefer to keep this PR scoped to only that command set for now. Having said that, the appropriate place to make this change would likely be in this function:
https://github.com/operator-framework/operator-sdk/blob/6a6edfd34ccbd82b7ba6be6f7c07da9d7f764d5c/internal/olm/operator/config.go#L67-L113

IIRC this configuration type is the configuration that is used for both `operator-sdk run bundle` and `operator-sdk run bundle-upgrade` commands so modifying this `Configuration.Load()` function should help address the issue you outlined in the PR description.

2023-09-06 19:49 UTC, sebsoto commented
/remove-lifecycle stale

2023-09-06 19:51 UTC, sebsoto commented on internal/olm/installer/manager.go
Thanks for the review, sorry it took so long for me to get back to this. I took a crack at moving the change to the file you suggested. 

Please let me know if I'm misusing the overrides struct, I wasn't sure if this would be the correct way to set the timeout.

2023-09-20 13:00 UTC, sebsoto commented
@everettraven Could you take another a look at this when you get a chance? Thanks!

2023-10-20 13:48 UTC, everettraven approved these changes

2023-10-20 13:49 UTC, everettraven commented
Looks like the actions here are stuck. Going to close and re-open to kick them

2024-03-20 00:00 UTC, closed without merging