Documentation fix
operator-framework/operator-sdk pull request #6492
Opened 2023-07-06 12:44 UTC by PureRaidenCloud

**Description of the change:**
* Delete `_internal/google_news.html` since its deprecated.
* Update '.URL' to '.Permalink' since it can’t evaluate field URL in type *hugolib.pageState.
* Update Go version from '1.18' tp '1.19' in `building-operator` section.

**Checklist**
- [x] I've built and serve your docs to localhost:1313.
- [x] Version of Go has successfully updated.

2023-07-14 13:25 UTC, everettraven commented
@PureRaidenCloud It looks like the `sanity / sanity` check is failing due to a tag issue. In order to fix this I believe you need to fetch the latest changes from `master` and perform a rebase.

2023-07-14 13:27 UTC, everettraven approved these changes
These changes look good to me. In order for the changes to be reflected in the v1.30.x branch we will have to cherry pick this. After that I _think_ a Netlify admin needs to kick off a rebuild for that subdomain

2023-07-17 18:59 UTC, rashmigottipati commented
@PureRaidenCloud can you please signoff the commit using `git commit -s`.

2023-07-18 00:41 UTC, PureRaidenCloud commented
> @PureRaidenCloud can you please signoff the commit using `git commit -s`.

Hi @rashmigottipati, I've signed my commits.

2023-07-18 14:33 UTC, everettraven requested changes
@PureRaidenCloud It looks like a rebase may have gone wrong.  currently looks like there are changes that have already been merged and are more than just documentations.

Holding this PR until the issue is fixed:
/hold

2023-07-20 12:51 UTC, PureRaidenCloud commented
> @PureRaidenCloud It looks like a rebase may have gone wrong. currently looks like there are changes that have already been merged and are more than just documentations.

Hi @everettraven , I've updated changes this MR, please review it again.

2023-07-20 12:53 UTC, rashmigottipati approved these changes
/lgtm

2023-07-20 12:53 UTC, rashmigottipati commented
/hold cancel

2023-07-20 13:13 UTC, everettraven approved these changes

2023-07-20 13:13 UTC, merged

2023-07-20 13:14 UTC, everettraven commented
/cherrypick v1.30.x