Make `bundle run` init image choosable
operator-framework/operator-sdk pull request #6605
Opened 2023-10-13 14:13 UTC by sebsoto

**Description of the change:**
The  `--init-image` argument  has been added to the `run bundle` command. This argument will override the docker.io/library/busybox image, used when creating a registry pod. Not including the argument will cause the same behavior as before this change.

**Motivation for the change:**
The forced use of the image docker.io/library/busybox causes issues for users making use of operator-sdk run bundle. Dockerhub rate limits container image pulls. The rate limiting will cause operator-sdk run bundle to fail once `run bundle` has been used too many times within a time period.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

Closes #6578

2023-10-13 20:00 UTC, everettraven requested changes
Thanks for creating this PR @sebsoto ! This contribution is going to be a big help!

The general changes look great, but I did notice that the flag name `init-image` and it's current description are pretty vague. I think that in this case it is important to be more descriptive and explicit in the expectations that are made when this image is used so that users don't assume that any image will work here.

2023-10-17 14:58 UTC, sebsoto commented on internal/olm/operator/bundle/install.go
> +	fs.StringVar(&i.InitImage, "init-image", fbcutil.DefaultInitImage, "init image used to prepare the bundle")
Thanks @everettraven, I agree with those changes and I've added them in the most recent  revision. PTAL when you get a chance

2023-10-17 19:25 UTC, everettraven approved these changes
Looks good to me! Thanks for this contribution @sebsoto !

2023-10-17 19:26 UTC, everettraven commented
/lgtm

2023-10-18 15:43 UTC, sebsoto commented
Looks like the e2e and integration tests did not pass.
It seems like infrastructure issues to me but i'm not well versed in these tests

2023-10-19 16:38 UTC, merged

2023-11-08 08:29 UTC, KeenonLee commented
https://issues.redhat.com/browse/OCPBUGS-17961